name: CouplesQuest
options:
  bundleIdPrefix: com.damienhosea
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

targets:
  CouplesQuest:
    type: application
    platform: iOS
    sources:
      - path: CouplesQuest
        excludes:
          - "**/*.xcassets"
    resources:
      - path: CouplesQuest/Resources/Colors.xcassets
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        PRODUCT_BUNDLE_IDENTIFIER: com.damienhosea.CouplesQuest
        PRODUCT_NAME: CouplesQuest
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentGold
    info:
      path: CouplesQuest/Info.plist
      properties:
        CFBundleDisplayName: CouplesQuest
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
